config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' , to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  #login / logout 
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except:[:new] # post 'users' to: 'users#cretae'
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true,length: {minimum: 2,maximum: 100}
  validates :description, presence: true,length: {minimum:5,maximum: 1000}
  validates :user_id, presence: true
  
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :username ,presence: true, uniqueness: {case_sensitive: false},
            length: {minimum: 4, maximum: 25}
            
  VALIDATION_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email , presence: true, uniqueness: {case_sensitive: false},
            length: {maximum: 100},format: {with: VALIDATION_EMAIL_REGEX }
            
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger]="You Must Login For This Action"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_articles, only: [:update,:edit,:show,:destroy]
  before_action :require_user, except: [:index,:show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] ="Article Was Successfully Added !"
      redirect_to article_path(@article)
    else
      flash[:danger] ="Somthing went wrong !! "
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article Updation Done !"
      redirect_to article_path(@article)
    else
      flash[:danger] = "Somthing went Wrong !!"
      render 'edit'
    end
  end

  def edit
  end

  def show
  end

  def index
    # @article = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    if(@article.destroy)
      flash[:success] = "Article Deleted Successfully !"
    else
      flash[:danger] = "Something went wrong !!"      
    end
    redirect_to articles_path
  end
  private
  
  def set_articles
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end
  
  def require_same_user
    if current_user != @article.user
      flash[:danger] = "You Can Only Edit Or Delete Your Own Article"
      redirect_to article_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.paginate(page: params[:page],per_page: 6)
  end
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] ="Category Added Successfully !!"
      redirect_to articles_path
    else
      flash[:danger] ="Somthing Went Wrong !!"
      render 'new'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page],per_page: 3)
  end
  
  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] ="Category Deleted Successfully !!"
      redirect_to categories_path
    else
       flash[:danger] ="Somthing Went Wrong !!"
       render 'index'
    end
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
  def about
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if (user && user.authenticate(params[:session][:password]))
      session[:user_id] = user.id
      flash[:success] = "Wellcome, you have successfully loged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] ="Wrong Login Information !!"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] ="You have Loged Out !"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user , only: [:edit, :show ,:update]
  before_action :require_same_user, only:[:edit, :update] 
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]="Successfully Added. Login with the user Name : #{@user.username}"
      redirect_to login_path
    else
      flash[:danger]="Somthig went wrong !! "
      render 'new'
    end
  end
  
  def edit
  end
  
  def show
    @user_articles = @user.articles.order(created_at: :desc).paginate(page: params[:page], per_page: 3)
  end
  
  def index
    @users = User.where.not(email: current_user.email).paginate(page: params[:page], per_page: 3)
  end
  
  def update
    if @user.update(user_params)
      flash[:success]="User was updated successfully !!"
      redirect_to articles_path
    else
      flash[:danger]="Somthig went wrong !! "
      render 'edit'
    end
  end
  def destroy
    @user = User.find(params[:id])
    if current_user != @user
      if @user.destroy 
        session[@user.id]=nil
        flash[:success]="User Deleted Successfully !!"
        redirect_to users_path
      end
    else
      flash[:danger] ="Can't Delete this User"
      redirect_to root_path
    end
  end
  
  private
  
  def set_user
    @user  = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:username,:email, :first_name, :last_name, :password)
  end
  def require_same_user
    if current_user != @user
      flash[:danger] ="You Can Oly Edit Ypur Own Account"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_articles.html.erb
<% obj.each do |articles|%>
<div class="row">
	<div class="col-xs-10 col-sm-offset-1">
		<div class="well well-lg">
			<div class="row floatset">
				<%if articles.categories.length > 0%><b>Categories :</b><% end %>
				<% articles.categories.each do |cn|%>
					<%= link_to cn.name, category_path(cn),class: "btn-primary btn-sm" %>
				<% end %>
			</div>
			<div class="article-title">
				<%= link_to articles.title, article_path(articles)%>
			</div>
			<div class="article-des">
				<p><%= truncate(articles.description, length: 100)%></p>
				<p><small class="rightsmall">Created By : <%= link_to articles.user.first_name+" "+articles.user.last_name, user_path(articles.user)%></small></p>
				<p><small class="leftsmall">Last Update : <%= time_ago_in_words(articles.updated_at)%> ago</small></p>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/articles/_form.html.erb
<div class='row'>
	<div class='col-xs-12'>
		<%= form_for(@article, :html => {class: "form-horizontal",role: "form"}) do |f|%>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :title %>
			</div>
			<div class="control-label col-sm-4">
				<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :description %>
			</div>
			<div class="col-sm-8">
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label Category.name %>
			</div>
			<div class="col-sm-8">
				<div class="row">
					<div class="col-sm-12">
						<%= f.collection_check_boxes :category_ids, Category.all,:id,:name do |cb|%>
						<%cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: 'btn btn-primary btn-lg' %>
			</div>
		</div>
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<div align="center">
	<%= will_paginate %>
</div>
<% if @articles.length > 0%>
	<%= render 'articles', obj: @articles%>
<% else %>
	<%= render 'layouts/emptydata'%>
<% end %>
<div align="center">
	<%= will_paginate %>
</div> 

app/views/articles/new.html.erb
<h1>Creta New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2><b><%= @article.title%></b><small>(Titile)</small></h2>
<div class="leftsmall"><%@article.categories.each do |c|%><%= link_to c.name, category_path(c),class:"btn-primary btn-sm"%> <% end %></div>
<hr />
<div class="col-xs-2 col-sm-offset-0">
	<b>Description :-</b>
</div>
<div class="col-xs-8 col-sm-offset-0">
	<p>
		<label><%= @article.description%></label>
	</p>
</div>
<div class="well col-xs-12 col">
	<% if logged_in? && current_user == @article.user %>
	<%= link_to 'Edit This Articles' ,edit_article_path(@article), class:'btn btn-xl btn-primary' %>
	<%= link_to 'Delete This Article' ,article_path(@article),method: :delete ,data: {confirm: "Are You Sure ?"}, class:'btn btn-xl btn-danger' %>
	<% end %>
	<%= link_to 'Show All Articles' ,articles_path, class:'btn btn-xl btn-success' %>

</div>

app/views/categories/index.html.erb
<h1>All Categories</h1>
<hr />
<div class="row">
	<div class="col-sm-12">
		<%@categories.each do |cat|%>
		<div class="well col-md-3 col-md-offset-1">
			<div class="leftsmall">
				<%if current_user.admin? %>
					<%= link_to category_path(cat),method: :delete ,data: {confirm: "Are You Sure ?"} do %>
					<div class="closeImg"><!-- Image Div For Close Btn --></div>
					<% end %>
				<% end %>
			</div>
			<%= link_to category_path(cat) do %>
			<h1><b><%= cat.name%></b></h1>
			<% end %>
			<small><%= "("+pluralize(cat.articles.count,"article")+")"%></small>
		</div>
		<% end %>
	</div>
	<div align="right">
		<%= will_paginate %>
	</div>
</div>
<!-- <% @categories.each do |cat|%>
<div class="row">
<div class="col-md-12">
<div class="col-md-2">
<h4><b><%= link_to cat.name,"#" %> <small><%= "("+pluralize(cat.articles.count,"article")+")"%></small></b></h4>
</div>
</div>
<!-- <h4><b><%= link_to cat.name,"#" %> <small><%= "("+pluralize(cat.articles.count,"article")+")"%></small></b></h4>
</div>
<% end %>	-->

app/views/categories/new.html.erb
<h1>New Category</h1>
<div class='row'>
	<div class='col-xs-12'>
		<%= form_for(@category, :html => {class: "form-horizontal",role: "form"}) do |f|%>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :name %>
				</div>
				<div class="control-label col-sm-8">
					<%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit class: 'btn btn-primary btn-lg' %>
				</div>
			</div>
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<h1>Articles for <%= @category.name%> category</h1>
<% if @category_articles.length > 0 %>
<div align="center">
	<%= will_paginate @category_articles%>
</div>
<%= render 'articles/articles', obj: @category_articles%>
<div align="center">
	<%= will_paginate @category_articles%>
</div>
<% else %>
<%= render 'layouts/emptydata'%>
<% end %>

app/views/layouts/_emptydata.html.erb
<div align="center">
	<p class="emptydata"><b> No Data Found </b> </p>
</div>

app/views/layouts/_errorflash.html.erb
<% if ! @user.nil? %>
<ul>
	<% @user.errors.full_messages.each do |err|%>
	<li style="color: red">
		<%= err %>
	</li>
	<% end %>
</ul>
<% else if ! @article.nil? %>
<ul>
	<% @article.errors.full_messages.each do |err|%>
	<li style="color: red">
		<%= err %>
	</li>
	<% end %>
</ul>
<% else if !session.nil? %>

<% else %>

<% end %>
<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">

	<footer class="footer">

		<small> Copyright © <%= link_to 'The complete details on alpha blog','#'%> design by <%=link_to 'Sachin Saini','#'%> </small>

		<nav>

			<ul>

				<li>
					<%= link_to "About Alpha Blog", about_path %>
				</li>

			</ul>

		</nav>

	</footer>

</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-sm-offset-1">
		<% flash.each do |name,msg|%>
		<div class=" alert alert-<%= name%> ">
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg , :id => 'flash_#{name}' if msg.is_a?(String)%>
			<% if name == "danger"%>
			<%= render 'layouts/errorflash'%>
			<% end %>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<!-- <a class="navbar-brand" href="#">Alpha blog</a> -->
			<%= link_to 'ALPHA BLOG', root_path , class: 'navbar-brand', id: 'logo' %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to 'Articles' ,articles_path%>
				</li>
				<!-- <li>
					<%= link_to 'Users' ,users_path %>
				</li> -->
				<% if logged_in? %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to 'New Article' , new_article_path%>
						</li>
					</ul>
				</li>

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "All Categories", categories_path%>
						</li>
						<% if current_user.admin? %>
						<li>
							<%= link_to "Add New Category", new_category_path%>
						</li>
						<% end %>
						<li role="separator" class="divider"></li>
						<% Category.all.each do |cat|%>
						<li>
							<%= link_to cat.name, category_path(cat) %>
						</li>
						<% end %>
					</ul>
				</li>
				<% end %>
			</ul>
			<form class="navbar-form navbar-left">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">
					Submit
				</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<% if logged_in? %>
				<li>
					<a href=""><%= "Wellcome "+current_user.first_name.upcase+" "+current_user.last_name.upcase%> </a>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "Edit Profile", edit_user_path(current_user)%>
						</li>
						<li>
							<%= link_to "View Profile", user_path(current_user)%>
						</li>
						<% if current_user.admin? %>
							<li>
								<%= link_to "Manage Users",users_path%>
							</li>
						<% end %>
						<li role="separator" class="divider"></li>
						<li>
							<%= link_to 'Log out', logout_path, method: :delete %>
						</li>
					</ul>
				</li>
				<% else %>
				<li>
					<%= link_to 'SignUp / Login', login_path%>
				</li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>AlphaBlog</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<%= render 'layouts/navbar'%>
		<div class="container">
			<%= render 'layouts/messages'%>
			<%= yield %>
		</div>
		<%=render 'layouts/footer'%>
		<%= debug(params) if Rails.env.development?%>
	</body>
</html>

app/views/pages/about.html.erb
<h1>this is about Page</h1>

app/views/pages/home.html.erb
<html>
	<head>
		<title>Page Title</title>
		<style>
		</style>
	</head>
	<body">

		<div>
			<div class="center jumbotron">
				<h1>Alpha Blog</h1>
			</div>
		</div>
		<div>
			<div style="float: right; width: 49%">
				<h2> 1 Guide Assumptions</h2>
				<p>
					This guide is designed for beginners who want to get started with a Rails application from scratch. It does not assume that you have any prior experience with Rails.
				</p>
				<p>
					Rails is a web application framework running on the Ruby programming language. If you have no prior experience with Ruby, you will find a very steep learning curve diving straight into Rails. There are several curated lists of online resources for learning Ruby:
				</p>
			</div>
			<div style="float: left; width: 50%">
				<h1>2 What is Rails?</h1>
				<p>
					Rails is a web application development framework written in the Ruby programming language. It is designed to make programming web applications easier by making assumptions about what every developer needs to get started. It allows you to write less code while accomplishing more than many other languages and frameworks.
				</p>
				<p>
					By following along with this guide, you'll create a Rails project called blog, a (very) simple weblog. Before you can start building the application, you need to make sure that you have Rails itself installed.
				</p>

			</div>
		</div>
	</body>
</html>

app/views/users/_form.html.erb
<div class='row'>
	<div class='col-xs-12 col-xs-offset-2'>
		<%= form_for(@user, :html => {class: "form-horizontal",role: "form"}) do |f|%>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :username %>
				</div>
				<div class="control-label col-sm-4">
					<%= f.text_field :username, class: "form-control", placeholder: "User Name", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :email %>
				</div>
				<div class="col-sm-4">
					<%= f.email_field :email, class: "form-control", placeholder: "Your Email" %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :first_name %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :last_name %>
				</div>
				<div class="col-sm-4">
					<%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :password %>
				</div>
				<div class="col-sm-4">
					<%= f.password_field :password, class: "form-control", placeholder: "Your Password" %>
				</div>
			</div>
			<!-- <div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :Password %>
				</div>
				<div class="col-sm-4">
					<%= f.email_field :password, class: "form-control", placeholder: "Re-Enter Password" %>
				</div>
			</div> -->
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit(@user.new_record? ? "Sign Up" : "Update", class: 'btn btn-primary btn-lg col-xs-4')%>
				</div>
			</div>
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Back To Home Page", root_path %> ]
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1> Edit Account </h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1>All Alpha Bloggers</h1>
<div align="center">
	<%= will_paginate%>
</div>

<% @users.each do |u|%>
<!-- <ul class="listing">
<div class="row center">
<div class="well col-md-8 col-md-offset-2">
<div class="row">
<li><h2><%= link_to u.first_name+" "+u.last_name, user_path(u) %></h2></li>
<li> <%= link_to gravatar_for(u), user_path(u) %></li>
<li><%= link_to u.username, user_path(u) %></li>
<li><small><%= pluralize(u.articles.count, "article") if u.articles %></small></li>
</div>
</div>
</div>
</ul> -->
<div class="row center">
	<div class="well col-md-6 col-md-offset-3">
		<div class="well col-md-4 col-md-offset-1">
			<%= link_to gravatar_for(u), user_path(u) %>
		</div>
		<div class="row">
			<h2><%= link_to u.first_name+" "+u.last_name, user_path(u) %></h2>
			<small><b><%= pluralize(u.articles.count, "article") if u.articles %></b></small>
			<div class="row">
				<!-- <%=link_to "Edit", edit_user_path(u), class: "btn-primary btn-sm"%> -->
				<%=link_to "Delete",user_path(u),method: :delete ,data: {confirm: "Are you sure you want to delete this user ?"}, class: "btn-danger btn-sm"%>
			</div>
		</div>
	</div>
</div>
<% end %>

<div align="center">
	<%= will_paginate%>
</div>

app/views/users/login.html.erb
<h1>Login</h1>
<div class='row'>
	<div class='col-xs-12'>
		<%= form_for(@user, :html => {class: "form-horizontal",role: "form"}) do |f|%>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :username %>
				</div>
				<div class="control-label col-sm-4">
					<%= f.text_field :username, class: "form-control", placeholder: "User Name", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :password %>
				</div>
				<div class="col-sm-4">
					<%= f.password_field :password, class: "form-control", placeholder: "Your Password" %>
				</div>
			</div>
			<!-- <div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :Password %>
				</div>
				<div class="col-sm-4">
					<%= f.email_field :password, class: "form-control", placeholder: "Re-Enter Password" %>
				</div>
			</div> -->
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit "Login", class: 'btn btn-primary btn-lg' %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<p>Don't Have Alpha Account <%= link_to 'Sign Up', signup_path %> Here</p>
				</div>
			</div>
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Back To Home Page", root_path %> ]
		</div>
	</div>
</div>

app/views/users/new.html.erb
<h1> Sign Up Form</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1>User Details </h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @user %>
	</div>
</div>
<h3 align="center"><%=@user.first_name%>'s Article</h3>


<%= render 'articles/articles', obj: @user_articles%>
<div align="right">
	<%= will_paginate @user_articles %>
</div>